entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    http:
  mqtt:
    address: ":1883"

certificatesResolvers:
  duckdnsResolver:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      # Email address used for Let's Encrypt registration.
      email: "<YOUR_EMAIL>"

      # File or key used for certificates storage.
      # Recommended: give to the file permissions 600
      storage: "/etc/traefik/acme/acme.json"

      # The certificates' duration in hours.
      # It defaults to 2160 (90 days) to follow Let's Encrypt certificates' duration.
      # certificatesDuration: 2160

      # With duckdns, we use a DNS-01 ACME challenge
      # NB: don't forget to set your duckdns token in a DUCKDNS_TOKEN environment variable
      dnsChallenge:
        provider: "duckdns"
        # Wait x seconds before traefik checks the TXT record
        delayBeforeCheck: 20
log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
api:
  # Set to true allows to access the api without HTTPS
  insecure: true
  # Enable the dashboard service
  dashboard: true
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    # all the yml files found into this folder will be used as dynamic configuration
    # so you can split your services configuration in multiple files, one for each service
    # for an example, see /etc/traefik/dynamic/dashboard.yml
    directory: "/etc/traefik/dynamic"
    watch: true